[debug] [2020-11-25T07:33:59.512Z] ----------------------------------------------------------------------
[debug] [2020-11-25T07:33:59.513Z] Command:       /Users/camilo.mejia/.nvm/versions/node/v10.15.2/bin/node /Users/camilo.mejia/.nvm/versions/node/v10.15.2/bin/firebase deploy
[debug] [2020-11-25T07:33:59.514Z] CLI Version:   8.2.0
[debug] [2020-11-25T07:33:59.514Z] Platform:      darwin
[debug] [2020-11-25T07:33:59.514Z] Node Version:  v10.15.2
[debug] [2020-11-25T07:33:59.514Z] Time:          Wed Nov 25 2020 08:33:59 GMT+0100 (Central European Standard Time)
[debug] [2020-11-25T07:33:59.514Z] ----------------------------------------------------------------------
[debug] [2020-11-25T07:33:59.514Z] 
[debug] [2020-11-25T07:33:59.525Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-11-25T07:33:59.526Z] > authorizing via signed-in user
[debug] [2020-11-25T07:33:59.526Z] [iam] checking project connectron-b6160 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2020-11-25T07:33:59.527Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2020-11-25T07:33:59.528Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2020-11-25T07:33:59.763Z] <<< HTTP RESPONSE 200 {"date":"Wed, 25 Nov 2020 07:33:59 GMT","expires":"Mon, 01 Jan 1990 00:00:00 GMT","cache-control":"no-cache, no-store, max-age=0, must-revalidate","pragma":"no-cache","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-11-25T07:33:59.788Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/connectron-b6160:testIamPermissions  
 {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2020-11-25T07:34:01.818Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Wed, 25 Nov 2020 07:34:01 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=746","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-11-25T07:34:01.824Z] [iam] error while checking permissions, command may fail: FirebaseError: Authorization failed. This account is missing the following required permissions on project connectron-b6160:

  firebase.projects.get
  firebasehosting.sites.update
[debug] [2020-11-25T07:34:01.825Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/connectron-b6160  
 
[debug] [2020-11-25T07:34:02.330Z] <<< HTTP RESPONSE 403 {"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Wed, 25 Nov 2020 07:34:02 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-11-25T07:34:02.330Z] <<< HTTP RESPONSE BODY {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2020-11-25T07:34:02.333Z] HTTP Error: 403, The caller does not have permission
[debug] [2020-11-25T07:34:02.486Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at module.exports (/Users/camilo.mejia/.nvm/versions/node/v10.15.2/lib/node_modules/firebase-tools/lib/responseToError.js:38:12)
    at Request._callback (/Users/camilo.mejia/.nvm/versions/node/v10.15.2/lib/node_modules/firebase-tools/lib/api.js:41:35)
    at Request.self.callback (/Users/camilo.mejia/.nvm/versions/node/v10.15.2/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/camilo.mejia/.nvm/versions/node/v10.15.2/lib/node_modules/firebase-tools/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/camilo.mejia/.nvm/versions/node/v10.15.2/lib/node_modules/firebase-tools/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[error] 
[error] Error: Failed to get Firebase project connectron-b6160. Please make sure the project exists and your account has permission to access it.
